apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies
  labels:
    app: movies
    networking/allow-internet-egress: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec:
      containers:
        - name: movies
          image: 000094597749.dkr.ecr.us-east-1.amazonaws.com/movie-service:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: movie-service
spec:
  selector:
    app: movies
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-egress
spec:
  podSelector:
    matchLabels:
      name: movies
  policyTypes:
    - Egress
  egress:
    - {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-ingress
spec:
  podSelector:
    matchLabels:
      name: movies
  ingress:
    - {}
  policyTypes:
    - Ingress
