spring:
  data:
    mongodb:
      uri: MONDB-URL
      database: Movies
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

cloud:
  aws:
    credentials:
      access-key: AWS-ACCESS-KEY
      secret-key: AWS-SECRET-KEY
    region:
      static: us-east-1
    static:
      auto: false

application:
  bucket:
    name: movies-bucket-swamy
